version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3001:3001"
    command: bash -c "npm run build;npm run start"
    volumes:
      - .:/usr/src/app